### ISSUE TITLE
Stop using Visual Studio 2010. It's too old! :p

### ISSUE THREAD

**Issue by nmabhinandan** [sanjujosh/String-Quotter#1]
Seriously bro?

**Comment by sanjujosh** [comment]
Long story short, While trying to debug a production issue in the middle of the night thought of this idea, created this hacky tool. Only VS2010 was readily available. Case dismissed, installed VS2017  :smile:

**Comment by nmabhinandan** [comment]
Okay. Closing issue. 😂
